apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: apps-tenant
  annotations:
    kustomize.toolkit.fluxcd.io/force: "Enabled"
spec:
  validationFailureAction: Enforce
  background: false
  generateExisting: true
  rules:
    # This rule ensures that all namespaces belonging to the apps tenant
    # have a copy of the apps secrets from the flux-system namespace.
    - name: sync-apps-secrets
      match:
        any:
          - resources:
              kinds:
                - v1/Namespace
              selector:
                matchLabels:
                  toolkit.fluxcd.io/tenant: "apps"
      generate:
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        cloneList:
          namespace: flux-system
          kinds:
            - v1/Secret
          selector:
            matchLabels:
              toolkit.fluxcd.io/tenant: "apps"
    # This rule ensures that all HelmRepository belonging to the apps tenant
    # are of type OCI.
    - name: helm-oci-only
      match:
        any:
          - resources:
              kinds:
                - HelmRepository
              namespaceSelector:
                matchLabels:
                  toolkit.fluxcd.io/tenant: "apps"
      validate:
        message: "spec.type must be oci"
        anyPattern:
          - spec:
              type: "oci"
