---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-apps
  namespace: frontend
spec:
  interval: 1m
  ref:
    branch: ${branch}
  secretRef:
    name: flux-apps
  url: https://github.com/controlplaneio-fluxcd/d1-apps.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-frontend
  namespace: frontend
spec:
  targetNamespace: frontend
  serviceAccountName: flux-apps
  interval: 12h
  retryInterval: 3m
  path: ./components/frontend/${environment}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  timeout: 15m
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/serviceAccountName
          value: flux-apps
      target:
        kind: "(HelmRelease|Kustomization)"
