apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra-update-policies
spec:
  serviceAccountName: flux-infra
  interval: 12h
  retryInterval: 3m
  path: ./update
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
