apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra-automation
  namespace: flux-system
spec:
  serviceAccountName: flux-infra
  interval: 12h
  retryInterval: 3m
  path: ./update
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  timeout: 5m
  wait: true
