apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra-tenant
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 12h
  retryInterval: 3m
  wait: true
  timeout: 15m
  path: ./tenants/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
