apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ENVIRONMENT: "production"
  GIT_BRANCH: "production"
  CLUSTER_NAME: "prod-eu"
  CLUSTER_DOMAIN: "eu.example.com"
